namespace:
  name: openshift-nfd

operatorGroup:
  name: nfd-operator-group

subscription:
  name: nfd
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  startingCSV: nfd.4.18.0-202602261953
