enabled: true
namespace: openshift-nfd

instance:
  name: nfd-instance
  topologyUpdater: false
  # Passthrough labels for GPU nodes
  extraLabelNamespace: "nvidia.com/gpu"
  operand:
    image: registry.redhat.io/openshift4/ose-node-feature-discovery:v4.18
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist:
            - "03"
            - "02"
            - "12"
          deviceLabelFields:
            - vendor

cluster: {}
