---
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: {{ .Values.clusterPolicy.name }}
  namespace: {{ .Values.namespace }}
spec:
  driver:
    enabled: {{ .Values.clusterPolicy.driver.enabled }}
    image: {{ .Values.clusterPolicy.driver.image }}
    upgradePolicy:
      autoUpgrade: {{ .Values.clusterPolicy.driver.upgradePolicy.autoUpgrade }}
      drain:
        deleteEmptyDir: {{ .Values.clusterPolicy.driver.upgradePolicy.drain.deleteEmptyDir }}
        force: {{ .Values.clusterPolicy.driver.upgradePolicy.drain.force }}
        timeoutSeconds: {{ .Values.clusterPolicy.driver.upgradePolicy.drain.timeoutSeconds }}
      maxParallelUpgrades: {{ .Values.clusterPolicy.driver.upgradePolicy.maxParallelUpgrades }}
      podDeletion:
        deleteLatest: {{ .Values.clusterPolicy.driver.upgradePolicy.podDeletion.deleteLatest }}
        force: {{ .Values.clusterPolicy.driver.upgradePolicy.podDeletion.force }}
        timeoutSeconds: {{ .Values.clusterPolicy.driver.upgradePolicy.podDeletion.timeoutSeconds }}
      waitForCompletion: {{ .Values.clusterPolicy.driver.upgradePolicy.waitForCompletion }}
  devicePlugin:
    enabled: {{ .Values.clusterPolicy.devicePlugin.enabled }}
    gfd:
      enabled: {{ .Values.clusterPolicy.devicePlugin.gfd.enabled }}
      resources:
        {{- .Values.clusterPolicy.devicePlugin.gfd.resources | toYaml | nindent 8 }}
  dcgm:
    enabled: {{ .Values.clusterPolicy.dcgm.enabled }}
  migManager:
    enabled: {{ .Values.clusterPolicy.migManager.enabled }}
  sandboxDevicePlugin:
    enabled: {{ .Values.clusterPolicy.sandboxDevicePlugin.enabled }}
  sriovDevicePlugin:
    enabled: {{ .Values.clusterPolicy.sriovDevicePlugin.enabled }}
  vgpuDeviceManager:
    enabled: {{ .Values.clusterPolicy.vgpuDeviceManager.enabled }}
  vgpuManager:
    enabled: {{ .Values.clusterPolicy.vgpuManager.enabled }}
  vfioManager:
    enabled: {{ .Values.clusterPolicy.vfioManager.enabled }}
  toolkit:
    enabled: {{ .Values.clusterPolicy.toolkit.enabled }}
  validator:
    plugin:
      env:
        {{- .Values.clusterPolicy.validator.plugin.env | toYaml | nindent 8 }}
