enabled: true
namespace: openshift-nmstate

olm:
  channel: stable
  approval: Automatic
  catalogSource: redhat-operators
  catalogSourceNamespace: openshift-marketplace
  startingCSV: kubernetes-nmstate-operator.v4.18.0
  operatorGroup: ""

cluster: {}
