enabled: true
namespace: nvidia-gpu-operator

clusterPolicy:
  name: gpu-cluster-policy
  driver:
    enabled: true
    image: nvidia/driver:560.35.03-rhel9
    upgradePolicy:
      autoUpgrade: false
      drain:
        deleteEmptyDir: false
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      podDeletion:
        deleteLatest: false
        force: true
        timeoutSeconds: 300
      waitForCompletion: true
  devicePlugin:
    enabled: true
    gfd:
      enabled: true
      resources:
        - name: nvidia.com/gpu
          replicas: 1
  dcgm:
    enabled: true
  migManager:
    enabled: false
  sandboxDevicePlugin:
    enabled: false
  sriovDevicePlugin:
    enabled: false
  vgpuDeviceManager:
    enabled: false
  vgpuManager:
    enabled: false
  vfioManager:
    enabled: false
  toolkit:
    enabled: true
  validator:
    plugin:
      env:
        - name: WITH_WORKLOAD
          value: "false"

cluster: {}
