---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd-operator
  namespace: {{ .Values.namespace }}
  labels:
    operators.coreos.com/nfd-operator.{{ .Values.namespace }}: ""
spec:
  channel: {{ .Values.olm.channel }}
  installPlanApproval: {{ .Values.olm.approval }}
  name: nfd-operator
  source: {{ .Values.olm.catalogSource }}
  sourceNamespace: {{ .Values.olm.catalogSourceNamespace }}
  {{- if .Values.olm.startingCSV }}
  startingCSV: {{ .Values.olm.startingCSV }}
  {{- end }}
