apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- if or .Values.namespace.labels .Values.commonLabels }}
  labels:
    {{- range $key, $val := .Values.namespace.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- range $key, $val := .Values.commonLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  {{- if or .Values.namespace.annotations .Values.commonAnnotations }}
  annotations:
    {{- range $key, $val := .Values.namespace.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- range $key, $val := .Values.commonAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
