apiVersion: nfd.openshift.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: ibm.ilmt.capacity-sockets
  namespace: {{ .Values.nodeFeatureRuleNamespace }}
spec:
  rules:
    - name: "ibm.ilmt.capacity-sockets"
      labelsTemplate: |
        {{ "{{" }} range .cpu.topology }}ibm.ilmt.{{ "{{" }} .Name }}={{ "{{" }} .Value }}
        {{ "{{" }} end }}
      matchFeatures:
        - feature: cpu.topology
          matchExpressions:
            socket_count: { op: Exists }
