enabled: true
namespace: hcl-bigfix

serviceAccount:
  name: bigfix-agent-sa

image:
  repository: registry.redhat.io/bigfix/besclient
  tag: 11.0.0
  pullPolicy: IfNotPresent

# PEM-encoded actionsite.afxm masthead configuration for the BigFix Client.
# This contains the public keys and connection endpoints for the BigFix server.
masthead:
  actionsite: |
    IP:bigfix-server.yourdomain.com:52311
    # Example ActionSite Masthead content. Put your actual actionsite.afxm contents here.

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

cluster: {}
